---
title: "Compare scenarios - landscape variables"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r, echo = FALSE}
### NAME OF SCENARIOS ####
mgmt.scenarios <- c("210913_conserv_current_MIROC5",
                    "210913_conserv_rcp45_MIROC5",
                    "210913_conserv_rcp85_MIROC5",
                    "210913_nomanag_current_MIROC5",
                    "210913_nomanag_rcp45_MIROC5",
                    "210913_nomanag_rcp85_MIROC5",
                    "210913_proactive_current_MIROC5",
                    "210913_proactive_rcp45_MIROC5",
                    "210913_proactive_rcp85_MIROC5",
                    "210913_proactiveplus_current_MIROC5",
                    "210913_proactiveplus_rcp45_MIROC5",
                    "210913_proactiveplus_rcp85_MIROC5")

### SETUP 
library(dplyr)
library(ggplot2)
library(reshape2)

di <- "/Users/maria.suarez.munoz/Google Drive/proj_LANDIS/experiments/"

cols <- c("conserv" = "#33A02C", # dark green
          "proactive" = "#6A3D9A", # dark purple
          "proactiveplus" = "#FF7F00", # orange
          "nomanag" = "#E31A1C") # red
lines <- c("current" = "solid", "rcp45" = "dotdash", "rcp85" = "dashed")

```

## AGBiomass
```{r, echo = FALSE}
agb <- data.frame()
for (i in 1:length(mgmt.scenarios)) {
  temp <- read.table(paste(di, mgmt.scenarios[i], "/output/agbiomass/AGBiomassAllYears.csv", sep =""), sep = ",", header = TRUE) %>%
    mutate(Scenario = paste(strsplit(mgmt.scenarios[i], split = "_")[[1]][2], strsplit(mgmt.scenarios[i], split = "_")[[1]][3], sep = "_"),
           Harv_scenario = strsplit(mgmt.scenarios[i], split = "_")[[1]][2],
           Clim_scenario = strsplit(mgmt.scenarios[i], split = "_")[[1]][3])
  agb <- rbind(agb, temp)
}

agb <- melt(agb, id.vars = c("Time", "Scenario", "Harv_scenario", "Clim_scenario"))

agb %>%
  filter(variable == "qilexg.m2" | variable == "qfagineag.m2" | variable == "qpyrenaicag.m2") %>%
 # filter(variable == "pnigrag.m2" | variable == "ppinasterg.m2"| variable == "psylvestrisg.m2" | variable == "phalepensisg.m2") %>%
  # filter(variable == "shortg.m2" | variable == "mediumg.m2"| variable == "tallg.m2") %>%
  # filter(variable == "jcommunisg.m2" | variable == "joxycedrusg.m2") %>%
  # filter(variable == "popnigrag.m2") %>%
  ggplot(aes(x = Time, y = value, group = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  facet_wrap(variable ~ ., scales = "free_y") +
  theme_classic() +
  theme(legend.position = "bottom") +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines)
```

## Total Cohorts
```{r, echo = FALSE}
coh <- data.frame()
for (i in 1:length(mgmt.scenarios)) {
  temp <- read.table(paste(di, mgmt.scenarios[i], "/output/TotalCohorts.txt", sep =""), sep = ",", skip = 1) %>%
     mutate(Scenario = paste(strsplit(mgmt.scenarios[i], split = "_")[[1]][2], strsplit(mgmt.scenarios[i], split = "_")[[1]][3], sep = "_"),
           Harv_scenario = strsplit(mgmt.scenarios[i], split = "_")[[1]][2],
           Clim_scenario = strsplit(mgmt.scenarios[i], split = "_")[[1]][3])
  colnames(temp) <- c("Time", "Cohorts", "AverageAge", "AverageB.g.m2.", "AverageLAI.m2.", "AverageWater.mm.", "SubCanopyPAR.W.m2.", "Litter.kgDW.m2.", "WoodyDebris.kgDW.m2.", "AverageBelowGround.g.m2.", "AverageFoliage.g.m2.", "AverageNSC.gC.m2.", "AverageAET.mm.", "Scenario", "Harv_scenario", "Clim_scenario") 
   
  coh <- rbind(coh, temp)
}

ggplot(coh, aes(x = Time, y = Cohorts, color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  theme_classic() +
  ggtitle("Cohorts") +
  theme(legend.position = "bottom")

ggplot(coh, aes(x = Time, y = AverageAge, color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  theme_classic() +
  ggtitle("AverageAge") +
  theme(legend.position = "bottom")

ggplot(coh, aes(x = Time, y = AverageB.g.m2., color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  theme_classic() +
  ggtitle("AverageB.g.m2.") +
  theme(legend.position = "bottom")

ggplot(coh, aes(x = Time, y = AverageLAI.m2., color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  theme_classic() +
  ggtitle("AverageLAI.m2.") +
  theme(legend.position = "bottom")

ggplot(coh, aes(x = Time, y = AverageWater.mm., color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  theme_classic() +
  ggtitle("AverageWater.mm.") +
  theme(legend.position = "bottom")

ggplot(coh, aes(x = Time, y = SubCanopyPAR.W.m2., color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  theme_classic() +
  ggtitle("SubCanopyPAR.W.m2.") +
  theme(legend.position = "bottom")

ggplot(coh, aes(x = Time, y = Litter.kgDW.m2., color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  theme_classic() +
  ggtitle("Litter.kgDW.m2.") +
  theme(legend.position = "bottom")

ggplot(coh, aes(x = Time, y = WoodyDebris.kgDW.m2., color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  theme_classic() +
  ggtitle("WoodyDebris.kgDW.m2.") +
  theme(legend.position = "bottom")

ggplot(coh, aes(x = Time, y = AverageBelowGround.g.m2., color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  theme_classic() +
  ggtitle("AverageBelowGround.g.m2.") +
  theme(legend.position = "bottom")

ggplot(coh, aes(x = Time, y = AverageFoliage.g.m2., color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  theme_classic() +
  ggtitle("AverageFoliage.g.m2.") +
  theme(legend.position = "bottom")

ggplot(coh, aes(x = Time, y = AverageNSC.gC.m2., color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  theme_classic() +
  ggtitle("AverageNSC.gC.m2.") +
  theme(legend.position = "bottom")

ggplot(coh, aes(x = Time, y = AverageAET.mm., color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  theme_classic() +
  ggtitle("AverageAET.mm.") +
  theme(legend.position = "bottom")
```

## Mortality
```{r, echo = FALSE}
mort <- data.frame()
for (i in 1:length(mgmt.scenarios)) {
  temp <- read.table(paste(di, mgmt.scenarios[i], "/output/MortalityTable.txt", sep =""), sep = ",", header = TRUE) %>%
    mutate(Scenario = paste(strsplit(mgmt.scenarios[i], split = "_")[[1]][2], strsplit(mgmt.scenarios[i], split = "_")[[1]][3], sep = "_"),
           Harv_scenario = strsplit(mgmt.scenarios[i], split = "_")[[1]][2],
           Clim_scenario = strsplit(mgmt.scenarios[i], split = "_")[[1]][3])
  mort <- rbind(mort, temp)
}

mort_melt <- melt(mort, id.vars = c("Time", "Cause", "Scenario", "Harv_scenario", "Clim_scenario")) %>%
  filter(Cause == " Succession")

# jpeg(file = "/Users/maria.suarez.munoz/Google Drive/proj_LANDIS/experiments/outputs/Mortality_old_climate", width=12, height=8, units="in", res=300)
mort_melt %>%
  # filter(variable == "qilex" | variable == "qfaginea" | variable == "qpyrenaica") %>%
 # filter(variable == "pnigra" | variable == "ppinaster"| variable == "psylvestris" | variable == "phalepensis") %>%
  # filter(variable == "short" | variable == "medium"| variable == "tall") %>%
  # filter(variable == "jcommunis" | variable == "joxycedrus") %>%
  # filter(variable == "popnigra") %>%
ggplot(aes(x = Time, y = value, color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  facet_wrap(variable ~ ., scales = "free_y") +
  theme_classic() +
  ggtitle("Mortality") +
  theme(legend.position = "bottom")
# dev.off()
```

## Harvest
```{r, echo = FALSE}
harv <- data.frame()
for (i in 1:length(mgmt.scenarios)) {
  temp <- read.table(paste(di, mgmt.scenarios[i], "/output/harvest/summary-log.csv", sep =""), sep = ",", header = TRUE) %>%
    mutate(Scenario = paste(strsplit(mgmt.scenarios[i], split = "_")[[1]][2], strsplit(mgmt.scenarios[i], split = "_")[[1]][3], sep = "_"),
           Harv_scenario = strsplit(mgmt.scenarios[i], split = "_")[[1]][2],
           Clim_scenario = strsplit(mgmt.scenarios[i], split = "_")[[1]][3])
  harv <- rbind(harv, temp)
}

harv_summary <- harv %>%
  dplyr::select(-ManagementArea, -Prescription) %>%
  group_by(Time, Scenario, Harv_scenario, Clim_scenario) %>%
  summarise_all(sum)

ggplot(harv_summary, aes(x = Time, y = HarvestedSites, color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  theme_classic() +
  ggtitle("Harvested Sites") +
  theme(legend.position = "bottom")

ggplot(harv_summary, aes(x = Time, y = TotalCohortsPartialHarvest, color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  theme_classic() +
  ggtitle("Total Cohorts Partial Harvest") +
  theme(legend.position = "bottom")

ggplot(harv_summary, aes(x = Time, y = TotalBiomassHarvested, color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  theme_classic() +
  ggtitle("Total Biomass Harvested (Mg)") +
  theme(legend.position = "bottom")

coh_harvested <- harv_summary %>%
  dplyr::select(Time, Scenario, Clim_scenario, Harv_scenario, CohortsHarvested_jcommunis, CohortsHarvested_joxycedrus,
         CohortsHarvested_phalepensis, CohortsHarvested_pnigra, CohortsHarvested_ppinaster, CohortsHarvested_psylvestris,
         CohortsHarvested_popnigra,
         CohortsHarvested_qfaginea, CohortsHarvested_qilex, CohortsHarvested_qpyrenaica,
         CohortsHarvested_short, CohortsHarvested_medium, CohortsHarvested_tall) %>%
  melt(id.vars = c("Time", "Scenario", "Clim_scenario", "Harv_scenario"))

ggplot(coh_harvested, aes(x = Time, y = value, color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  facet_wrap(variable ~ ., scales = "free_y") +
  theme_classic() +
  ggtitle("Cohorts Harvested") +
  theme(legend.position = "bottom") +
  theme(legend.position = "bottom")

biomass_harvested <- harv_summary %>%
  dplyr::select(Time, Scenario, Clim_scenario, Harv_scenario, BiomassHarvestedMg_jcommunis, BiomassHarvestedMg_joxycedrus,
         BiomassHarvestedMg_phalepensis, BiomassHarvestedMg_pnigra, BiomassHarvestedMg_ppinaster, BiomassHarvestedMg_psylvestris,
         BiomassHarvestedMg_popnigra,
         BiomassHarvestedMg_qfaginea, BiomassHarvestedMg_qilex, BiomassHarvestedMg_qpyrenaica,
         BiomassHarvestedMg_short, BiomassHarvestedMg_medium, BiomassHarvestedMg_tall) %>%
  melt(id.vars = c("Time", "Scenario", "Clim_scenario", "Harv_scenario"))

biomass_harvested %>%
  filter(variable != "BiomassHarvestedMg_jcommunis" & variable != "BiomassHarvestedMg_joxycedrus" & variable != "BiomassHarvestedMg_popnigra") %>%
ggplot(aes(x = Time, y = value, color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  facet_wrap(variable ~ ., scales = "free_y") + #
  theme_classic() +
  ggtitle("Biomass Harvested (Mg)") +
  theme(legend.position = "bottom")
```

## Establishment
```{r, echo = FALSE}
est <- data.frame()
for (i in 1:length(mgmt.scenarios)) {
  temp <- read.table(paste(di, mgmt.scenarios[i], "/output/Establishment/Est_{timestep}.csv", sep =""), sep = ",", header = TRUE) %>%
    mutate(Scenario = paste(strsplit(mgmt.scenarios[i], split = "_")[[1]][2], strsplit(mgmt.scenarios[i], split = "_")[[1]][3], sep = "_"),
           Harv_scenario = strsplit(mgmt.scenarios[i], split = "_")[[1]][2],
           Clim_scenario = strsplit(mgmt.scenarios[i], split = "_")[[1]][3])
  est <- rbind(est, temp)
}

est_melt <- melt(est, id.vars = c("Time", "Scenario", "Harv_scenario", "Clim_scenario"))

est_melt %>%
  # filter(variable == "jcommunis" | variable == "joxycedrus") %>%
  # filter(variable == "ppinaster" | variable == "phalepensis" | variable == "psylvestris" | variable == "pnigra") %>%
  # filter(variable == "qilex" | variable == "qfaginea" | variable == "qpyrenaica") %>%
  # filter(variable == "short" | variable == "medium" | variable == "tall") %>%
  # filter(variable == "popnigra") %>%
  ggplot(aes(x = Time, y = value, color = Scenario)) +
  geom_line(aes(linetype = Clim_scenario, color = Harv_scenario)) +
  geom_point(aes(color = Harv_scenario)) +
  scale_color_manual(values = cols) +
  scale_linetype_manual(values = lines) +
  facet_wrap(variable ~ ., scales = "free_y") +
  theme_classic() +
  ggtitle("Establishment") +
  theme(legend.position = "bottom")
```
